steps:
- task: GitHubRelease@1
  displayName: 'Create $(VERSION) GitHub release'
  inputs:
    gitHubConnection: 'github connection 2'
    repositoryName: 'MaksimZhukov/toolcache-python-generation'
    target: $(Build.SourceVersion)
    tagSource: userSpecifiedTag
    tag: '$(VERSION)-$(Build.BuildNumber)'
    title: '$(VERSION)'
    assets: |
     $(Pipeline.Workspace)/*/*.Zip
