jobs:
- job: 'Create_GitHub_release_and_publish_assets'
  pool:
    name: Azure Pipelines
    vmImage: 'vs2017-win2016'
  steps:    
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'current'
      path: $(Build.BinariesDirectory)

  - task: GitHubRelease@1
    displayName: 'Create $(ToolVersion) GitHub release'
    inputs:
      gitHubConnection: 'github connection 2'
      repositoryName: 'MaksimZhukov/toolcache-python-generation'
      target: $(Build.SourceVersion)
      tagSource: userSpecifiedTag
      tag: '$(ToolVersion)-$(Build.BuildNumber)'
      title: '$(ToolVersion)'
      assets: |
       $(Build.BinariesDirectory)/*.Zip
